# ============================================
# StudyMate AI - Terms & Conditions
# ============================================

import streamlit as st


def show_terms_page(standalone=False):
    """Show Terms & Conditions"""

    if standalone:
        st.title("📋 Terms & Conditions")
        st.markdown(
            f"*Last updated: January 2025*"
        )
        st.divider()

    st.markdown("""
    <div style='background:white; border-radius:14px;
    padding:30px; box-shadow:0 2px 10px rgba(0,0,0,0.07);
    font-size:14px; line-height:1.9; color:#333'>

    <h3 style='color:#1565C0'>📋 StudyMate AI — Terms & Conditions</h3>
    <p style='color:gray; font-size:12px'>
        Last Updated: January 2025 | Version 1.0
    </p>

    <hr style='border:1px solid #E3F2FD; margin:16px 0'>

    <h4 style='color:#1565C0'>1. Acceptance of Terms</h4>
    <p>
    By creating an account on StudyMate AI, you confirm that you
    have read, understood, and agree to be bound by these Terms
    and Conditions. If you do not agree, please do not use this platform.
    </p>

    <h4 style='color:#1565C0'>2. Platform Purpose</h4>
    <p>
    StudyMate AI is a free educational platform designed to help
    Pakistani students prepare for exams through AI-generated MCQs,
    study notes, and practice assessments. The platform also provides
    a directory for students to connect with tutors and teachers.
    </p>

    <h4 style='color:#1565C0'>3. Account Types & Responsibilities</h4>
    <p>
    <b>Student Accounts:</b> Students may use all study features freely.
    Students are responsible for the accuracy of information provided
    during registration.<br><br>
    <b>Teacher/Tutor Accounts:</b> Teachers must provide accurate
    professional information. Misrepresentation of qualifications
    is strictly prohibited and may result in account termination.
    </p>

    <h4 style='color:#1565C0'>4. Teacher-Student Marketplace Disclaimer</h4>
    <p style='background:#FFF3E0; padding:12px; border-radius:8px;
    border-left:4px solid #FF9800'>
    ⚠️ <b>Important:</b> StudyMate AI provides a platform for students
    and teachers to discover each other. Any tutoring arrangements,
    payments, or agreements made between students and teachers are
    <b>entirely their own responsibility</b>. StudyMate AI bears
    <b>no responsibility</b> for any financial transactions, service
    quality, disputes, or outcomes arising from teacher-student
    arrangements made through this platform.
    </p>

    <h4 style='color:#1565C0'>5. AI-Generated Content Disclaimer</h4>
    <p>
    Content generated by StudyMate AI (MCQs, notes, solutions) is
    for educational assistance only. While we strive for accuracy,
    AI-generated content may contain errors. Students should verify
    important information with their teachers and official textbooks.
    StudyMate AI is not responsible for any academic outcomes based
    solely on AI-generated content.
    </p>

    <h4 style='color:#1565C0'>6. Privacy & Data</h4>
    <p>
    We collect minimal personal information necessary to provide
    our services. Your data is stored securely and is never sold
    to third parties. Study history and assessment data is used
    only to improve your personal learning experience.
    </p>

    <h4 style='color:#1565C0'>7. Acceptable Use</h4>
    <p>Users must NOT:</p>
    <ul>
        <li>Share false or misleading information</li>
        <li>Attempt to hack or compromise the platform</li>
        <li>Use the platform for commercial purposes without permission</li>
        <li>Post inappropriate or offensive content</li>
        <li>Create multiple accounts to abuse free features</li>
    </ul>

    <h4 style='color:#1565C0'>8. Account Termination</h4>
    <p>
    StudyMate AI reserves the right to suspend or terminate any
    account that violates these terms, without prior notice.
    </p>

    <h4 style='color:#1565C0'>9. Changes to Terms</h4>
    <p>
    These terms may be updated periodically. Continued use of the
    platform after changes constitutes acceptance of new terms.
    </p>

    <h4 style='color:#1565C0'>10. Contact</h4>
    <p>
    For any questions regarding these terms, use the
    Suggestion Box in the application sidebar.
    </p>

    <hr style='border:1px solid #E3F2FD; margin:16px 0'>
    <p style='text-align:center; color:gray; font-size:12px'>
        © 2025 StudyMate AI | Developed by Aftab Ahmed | Pakistan 🇵🇰
    </p>

    </div>
    """, unsafe_allow_html=True)


def show_terms_checkbox():
    """Compact terms checkbox for signup"""
    col1, col2 = st.columns([1, 10])
    with col1:
        agreed = st.checkbox("", key="terms_agreed")
    with col2:
        st.markdown("""
        <div style='padding-top:3px; font-size:13px'>
            I agree to the
            <a href='#' style='color:#1565C0'>
            Terms & Conditions
            </a>
            and confirm that all information provided is accurate.
            I understand StudyMate AI is not responsible for
            teacher-student arrangements made through this platform.
        </div>
        """, unsafe_allow_html=True)
    return agreed